server:
  port: 8080

spring:
  application:
      name: rede_solidaria
  datasource:
      url: jdbc:postgresql://localhost:5432/rede_solidaria
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      db: ${DATABASE_DB}
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true