server:
  port: 8080

spring:
  application:
      name: rede_solidaria
  datasource:
      url: jdbc:postgresql://postgres:5432/rede_solidaria
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  jpa:
      hibernate:
        ddl-auto: create-only;
        show-sql: true;